# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 55b39216d4b35cae32f1d76957f254a652a109111cae74ce94f6aaf2bee82d045eca46a732b0b92874bbf795fdbfd03413467ddf0d6a2b106b6fe23fad3910f3

test:
  secret_key_base: f8385af7ae8d41d73aadad460aedb62b424f51f6975ee57a7b92543e9ce2e5ecc196ddafa91ea6f846dddd3b94ef16c31b80693e3da5ec23f6b6184ff0dae4c5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
